### ISSUE TITLE
不支持https的视频投屏？

### ISSUE THREAD

**Issue by hupfei** [KeyYao/DLNAWrapper#3]
excecute "SetAVTransportURI" action error : "(null)", response data -- > <?xml version="1.0" encoding="utf-8" standalone="yes"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode><errorDescription>Not enough IN args, too many IN args, no IN arg by that name, one or more IN args are of the wrong data type. Only HTTP and file: resource identifiers are supported.</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
2017-07-14 14:35:36.418174+0800 DLNAWrapper[1125:196404] 设置 URL 失败

**Comment by KeyYao** [comment]
@hupfei 此错误是设备返回的，可能该设备不支持https，可以手动打印一下Device类的location，用浏览器访问此地址，可以查看到该设备的upnp相关信息

**Comment by hupfei** [comment]
http://192.168.2.24:43920/dev/5120f45b-1709-86ac-ffff-ffffc7831a22/desc.xml
这是location

**Comment by hupfei** [comment]
那怎么通过location看该设备是否支持https呢？看了location，并看不懂。。。

**Comment by KeyYao** [comment]
@hupfei 查看location ```<serviceList>```中 ```<serviceId>```包含AVTransport 的元素中的```<SCPDURL>```的值，然后替换location端口后面的path生成一条url，访问此url就能知道此设备支持的操作及操作对应的参数
所有数据都是xml格式的
猜测可能是设备上的播放器不支持https

**Comment by hupfei** [comment]
@KeyYao 小米盒子应该支持https吧
<service><serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType><serviceId>urn:upnp-org:serviceId:AVTransport</serviceId><controlURL>/dev/5120f45b-1709-86ac-ffff-ffffc7831a22/svc/upnp-org/AVTransport/action</controlURL><eventSubURL>/dev/5120f45b-1709-86ac-ffff-ffffc7831a22/svc/upnp-org/AVTransport/event</eventSubURL><SCPDURL>/dev/5120f45b-1709-86ac-ffff-ffffc7831a22/svc/upnp-org/AVTransport/desc.xml</SCPDURL></service>

**Comment by hupfei** [comment]
@KeyYao 
<action><name>SetAVTransportURI</name><argumentList><argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument><argument><name>CurrentURI</name><direction>in</direction><relatedStateVariable>AVTransportURI</relatedStateVariable></argument><argument><name>CurrentURIMetaData</name><direction>in</direction><relatedStateVariable>AVTransportURIMetaData</relatedStateVariable></argument></argumentList></action>

**Comment by KeyYao** [comment]
@hupfei 错误号```402```是表示参数错误，```Only HTTP and file: resource identifiers are supported.```提示了只支持了http和普通文件协议

**Comment by hupfei** [comment]
@KeyYao 所以肯定是设备的问题了？

**Comment by KeyYao** [comment]
@hupfei 这边没有对应的设备和https资源测试，所以不能肯定是设备问题
现在设置url的参数是按照标准的协议做的，也有可能存在考虑不周的情况，不过目前没时间和精力去深入研究这方面
有兴趣可以去查阅相关资料学习，如果发现此项目有不足的地方，欢迎pull request
