### ISSUE TITLE
投屏视频的时候会非常卡

### ISSUE THREAD

**Issue by lalaluya** [KeyYao/DLNAWrapper#4]
我用这种方式投屏视频的时候回非常卡，缓冲十几秒只能流畅播放两三秒钟，然后继续缓冲

**Comment by KeyYao** [comment]
@lalaluya 卡的话是网络或者播放器的问题，跟投屏没有关系

**Comment by lalaluya** [comment]
可是同样投屏小米电视，用小米的投屏就没问题，不过小米的投屏之前会有缓冲

**Comment by KeyYao** [comment]
@lalaluya DMC实现的投屏实际上也只是把视频的链接告诉播放器而已，播放器接收到链接后会加载并播放视频，实际的播放效果是播放器决定的，DMC无法干涉，DMC能操作的也只是暂停快进等简单的操作而已。
有兴趣可以去找资料理解一下DLNA的5个功能模块：DMS、DMR、DMC、DMP、DMPr

**Comment by chenyong123** [comment]
@lalaluya 您好，能联系下您么，我遇到点问题，三星电视投屏失败

**Comment by lalaluya** [comment]
@chenyong123 可以，加我qq吧 891803168
